version: '3.8'
services:
      app:
            build: .
            container_name: laravel_app
            volumes:
                  - .:/var/www
            ports:
                  - "8000:8000"
            depends_on:
                  - db
      db:
            image: mysql:8.0
            container_name: laravel_db
            restart: always
            environment:
                  MYSQL_ROOT_PASSWORD: root
                  MYSQL_DATABASE: perfectpay
                  MYSQL_USER: laravel_user
                  MYSQL_PASSWORD: secret
            ports:
                  - "3306:3306"
      test:
            image: php:8.2-cli
            container_name: laravel_tests
            volumes:
                  - .:/var/www
            working_dir: /var/www
            command: ["vendor/bin/phpunit"]
            depends_on:
                  - app

